name = "watsonia"
main = "dist/_worker.js"
compatibility_date = "2024-09-23"

# Assets
[site]
bucket = "./dist"

# 如果需要自定义域名，取消注释以下行
# routes = [
#   { pattern = "example.com" }
# ]

# 环境变量（如果需要）
# [vars]
# MY_VARIABLE = "production_value"

# 开发环境配置
[env.development]
# [env.development.vars]
# MY_VARIABLE = "development_value"
